# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

call_matching <- function(cov_to_drop, data, replace, covs) {
    .Call(`_FLAME_call_matching`, cov_to_drop, data, replace, covs)
}

get_BF <- function(cov_to_drop, data, replace, covs) {
    .Call(`_FLAME_get_BF`, cov_to_drop, data, replace, covs)
}

get_PE <- function(cov_to_drop, covs, holdout, PE_method, user_PE_fit, user_PE_fit_params, user_PE_predict, user_PE_predict_params) {
    .Call(`_FLAME_get_PE`, cov_to_drop, covs, holdout, PE_method, user_PE_fit, user_PE_fit_params, user_PE_predict, user_PE_predict_params)
}

